version: 2.1

orbs:
  jira: circleci/jira@2.1.0

jobs:
  jira:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - jira/notify:
          message: "Build finished successfully"
          project: "YOUR_PROJECT_KEY"
          issue: "YOUR_ISSUE_KEY"
          status: "Done"
          
workflows:
  version: 2
  build:
    jobs:
      - jira
